/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TrainingSessionService } from "../trainingSession.service";
import { TrainingSessionCreateInput } from "./TrainingSessionCreateInput";
import { TrainingSession } from "./TrainingSession";
import { TrainingSessionFindManyArgs } from "./TrainingSessionFindManyArgs";
import { TrainingSessionWhereUniqueInput } from "./TrainingSessionWhereUniqueInput";
import { TrainingSessionUpdateInput } from "./TrainingSessionUpdateInput";
import { FeedbackFindManyArgs } from "../../feedback/base/FeedbackFindManyArgs";
import { Feedback } from "../../feedback/base/Feedback";
import { FeedbackWhereUniqueInput } from "../../feedback/base/FeedbackWhereUniqueInput";

export class TrainingSessionControllerBase {
  constructor(protected readonly service: TrainingSessionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TrainingSession })
  async createTrainingSession(
    @common.Body() data: TrainingSessionCreateInput
  ): Promise<TrainingSession> {
    return await this.service.createTrainingSession({
      data: {
        ...data,

        trainee: data.trainee
          ? {
              connect: data.trainee,
            }
          : undefined,

        trainer: data.trainer
          ? {
              connect: data.trainer,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateTime: true,
        id: true,

        trainee: {
          select: {
            id: true,
          },
        },

        trainer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        venue: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TrainingSession] })
  @ApiNestedQuery(TrainingSessionFindManyArgs)
  async trainingSessions(
    @common.Req() request: Request
  ): Promise<TrainingSession[]> {
    const args = plainToClass(TrainingSessionFindManyArgs, request.query);
    return this.service.trainingSessions({
      ...args,
      select: {
        createdAt: true,
        dateTime: true,
        id: true,

        trainee: {
          select: {
            id: true,
          },
        },

        trainer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        venue: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async trainingSession(
    @common.Param() params: TrainingSessionWhereUniqueInput
  ): Promise<TrainingSession | null> {
    const result = await this.service.trainingSession({
      where: params,
      select: {
        createdAt: true,
        dateTime: true,
        id: true,

        trainee: {
          select: {
            id: true,
          },
        },

        trainer: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        venue: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTrainingSession(
    @common.Param() params: TrainingSessionWhereUniqueInput,
    @common.Body() data: TrainingSessionUpdateInput
  ): Promise<TrainingSession | null> {
    try {
      return await this.service.updateTrainingSession({
        where: params,
        data: {
          ...data,

          trainee: data.trainee
            ? {
                connect: data.trainee,
              }
            : undefined,

          trainer: data.trainer
            ? {
                connect: data.trainer,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateTime: true,
          id: true,

          trainee: {
            select: {
              id: true,
            },
          },

          trainer: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          venue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTrainingSession(
    @common.Param() params: TrainingSessionWhereUniqueInput
  ): Promise<TrainingSession | null> {
    try {
      return await this.service.deleteTrainingSession({
        where: params,
        select: {
          createdAt: true,
          dateTime: true,
          id: true,

          trainee: {
            select: {
              id: true,
            },
          },

          trainer: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          venue: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/feedbacks")
  @ApiNestedQuery(FeedbackFindManyArgs)
  async findFeedbacks(
    @common.Req() request: Request,
    @common.Param() params: TrainingSessionWhereUniqueInput
  ): Promise<Feedback[]> {
    const query = plainToClass(FeedbackFindManyArgs, request.query);
    const results = await this.service.findFeedbacks(params.id, {
      ...query,
      select: {
        comments: true,
        createdAt: true,
        id: true,
        rating: true,

        trainingSession: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/feedbacks")
  async connectFeedbacks(
    @common.Param() params: TrainingSessionWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        connect: body,
      },
    };
    await this.service.updateTrainingSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/feedbacks")
  async updateFeedbacks(
    @common.Param() params: TrainingSessionWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        set: body,
      },
    };
    await this.service.updateTrainingSession({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/feedbacks")
  async disconnectFeedbacks(
    @common.Param() params: TrainingSessionWhereUniqueInput,
    @common.Body() body: FeedbackWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feedbacks: {
        disconnect: body,
      },
    };
    await this.service.updateTrainingSession({
      where: params,
      data,
      select: { id: true },
    });
  }
}
